### PR TITLE
feat: added button to archive a project

### PR DESCRIPTION
**Pull request by oskarikerppo**

### CODE REVIEW

**Comment by oskarikerppo** [comment]
Screenshot from 2021-11-26 16-24-21

Added "Archive Project" button to project details page. The button tries to change the status of the project to "ARCHIVED". If this is successful, a modal is opened that informs the user that the status has changed.

Work to be done: 
1) it should be checked that the status is not already ARCHIVED before attempting to change the status
2) there should perhaps be a button to undo the change

**Comment by oskarikerppo** [comment]
Screenshot from 2021-11-29 09-57-48

31ffc3a

The arvhive button is (in my opinion) ready. It archives any unarchived project on button press. If the project is already archived, the front doesn't try to change the status, but displays a different text on the modal instead.

**Comment by LeadingMoominExpert** [comment]
Should the`Archive Project` button even be displayed if the project has already been archived?

**Comment by oskarikerppo** [comment]
> Should the`Archive Project` button even be displayed if the project has already been archived?

The archive button is hidden from archived projects in 31ffc3a. Also the project name is displayed in the modal.

**Review by LeadingMoominExpert — APPROVED** [review]

**Review by robertsiipola — APPROVED** [review]

**Pull request merged**
